---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
stringData:
  TAILSCALE_AUTH_KEY: {{ .Values.config.authKey }}
